name: Lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  proto:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1

      - name: run protolint
        uses: plexsystems/protolint-action@v0.7.0
        with:
          configDirectory: .
          srcDirectory: ./proto
