name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  js:
    name: Test (JS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test
  kotlin:
    name: Test (Kotlin)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Generate protobufs
        run: dev/kotlin/generate
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Gradle Run Tests
        run: ./gradlew kotlin:test
